### ISSUE TITLE
Missing data for S4T10

### ISSUE THREAD

**Issue by sscolaro** [tbep-tech/seagrasstransect-dash#10]
@fawda123 Transect S4T10 location and historical data are not being displayed on shiny app. Historical data found in the [transect data portal](http://dev.seagrass.wateratlas.usf.edu/monitoring/assessments).

Location of S4T10 below.
![image](https://user-images.githubusercontent.com/72457078/202276532-8f44009b-c9a2-46c4-9b5f-5ea96b6341ae.png)

**Comment by fawda123** [comment]
@sscolaro good catch, I use two shapefiles on the T drive to build datasets in tbeptools that have transect locations as points and lines.  My guess is S4T10 was never in these shapfiles.  We'll have to fix this when we're both back in the office, likely after the holiday.

**Comment by fawda123** [comment]
@sscolaro S4T10 data are now on the dashboard.
