### ISSUE TITLE
Individual transect legend not displaying BB bins

### ISSUE THREAD

**Issue by sscolaro** [tbep-tech/seagrasstransect-dash#11]
@fawda123 Legend on the Individual Transect tab is not displaying the BB abundance bins but instead is displaying the species colors.

<img width="61" alt="image" src="https://user-images.githubusercontent.com/72457078/204351259-93babad9-0298-41f2-8866-77c15b5a366e.png">

**Comment by fawda123** [comment]
@sscolaro this is an issue converting a ggplot2 object to plotly (the interactive version).  

The ggplot2 version looks like this: 
![image](https://user-images.githubusercontent.com/3086881/204582635-2fb991ba-0e07-4685-a5f0-e79c8da11a0a.png)
And the same plot converted to plotly looks like this: 
![image](https://user-images.githubusercontent.com/3086881/204582931-2b93dff4-170f-437a-8500-af82172ea5b2.png)

The plotly version combines both legends from ggplot, where the size is the average abundance for a species.  I don't think there's anything I can do about this, other than show the ggplot version that is not interactive.  You can always see the abundance values by hovering the mouse over a point on the plot. 

A similar issue is noted here: https://stackoverflow.com/questions/66176949/why-is-ggplotly-ruining-my-legends-from-ggplot
