### ISSUE TITLE
2019 QAQC: S1T5

### ISSUE THREAD

**Issue by esherwoo77** [tbep-tech/seagrasstransect-dash#2]
@Gmangrove & @fawda123 : Please check that the 2019 data for S1T5 was correctly entered and assigned to the right transect. It appears that it could be data for another transect (references seagrass out to 1000m when all other historic measurements only capture data up to 500m).

**Comment by fawda123** [comment]
Looks like that's coming from the raw data in the Water Atlas, not something that was done during processing.  The tail end of it: 
![image](https://user-images.githubusercontent.com/3086881/111478161-2ed1ff80-8706-11eb-9b45-af85ec269a52.png)
