### ISSUE TITLE
WiP polygon drawing & seagrass cover prototype?

### ISSUE THREAD

**Issue by 7yl4r** [tbep-tech/seagrasstransect-dash#3]
Hi again Marcus! I'm interested in the (shiny?) code for that WiP polygon drawing & seagrass cover prototype shown in your presentation today. I don't see it here. Is it elsewhere? Perhaps you could add it on a dev branch here? Our MBON project has discussed creating something similar so perhaps we can collaborate on this.

**Comment by fawda123** [comment]
Hey Tyler!  Yea, that one is here: https://github.com/tbep-tech/seagrasscoverage-dash and the dashboard is here: http://shiny.tbep.org/seagrasscoverage-dash/

It uses the [mapedit](https://github.com/r-spatial/mapedit) package, which I thought was pretty well-known, but everytime I show that slide someone asks about it!

**Comment by 7yl4r** [comment]
Thank you!
