### ISSUE TITLE
Year with XXXX.5

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/seagrasstransect-dash#4]
On Tab 2, 'Individual transects', when years slider is < 8 years (eg 2015-2020), a '.5' appears on the FO graph at the bottom between each sampling year (eg 2015, 2015.5, 2016, 2016.5, 2017)

**Comment by fawda123** [comment]
@Gmangrove just pushed a fix to plotting function from tbeptools https://github.com/tbep-tech/tbeptools/commit/af68ff30442f8e5fd6d7e4c40f380d886d1fe589
