### ISSUE TITLE
Color change for species

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/seagrasstransect-dash#5]
The colors for Halodule and Caulerpa are extremely similar (at least to my poor old eyes), suggest changing to something different, also Halophila and Ruppia, Maybe more starkly different colors for all species?

**Comment by fawda123** [comment]
Working on this now: [0b4237736e0d80bb93127505d6bb75eda48cfddb](https://github.com/tbep-tech/tbeptools/commit/0b4237736e0d80bb93127505d6bb75eda48cfddb)

**Comment by fawda123** [comment]
It's done:
![image](https://user-images.githubusercontent.com/3086881/150609015-4a459499-aef9-48e6-a4c1-eb4f1e96a03f.png)
