### ISSUE TITLE
2021 Piney Point data being displayed

### ISSUE THREAD

**Issue by sscolaro** [tbep-tech/seagrasstransect-dash#9]
@fawda123 Initial Piney Point data collected on April 7, 2021 and April 8, 2021 using the [seagrass transect monitoring data portal](http://dev.seagrass.wateratlas.usf.edu/monitoring/assessments) is being pulled onto the [shiny app](https://shiny.tbep.org/seagrasstransect-dash/?_ga=2.120171464.1969136804.1654623172-1584753368.1630003506#section-individual-transects) resulting in 5 transects with multiple BB abundances being displayed for each seagrass spp. Can we filter Piney Point data out?

![2022-11-16 (2)](https://user-images.githubusercontent.com/72457078/202209406-e99802bc-2ca6-48bd-8407-f5263347487f.png)
![2022-11-16 (4)](https://user-images.githubusercontent.com/72457078/202210040-2a2fbb41-cbdd-4254-98fd-7fdd93c53693.png)

**Comment by fawda123** [comment]
Thanks @sscolaro, the PP data should now be removed from the dashboard.
